AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Lint/MissingSuper:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false