require:
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'test_*.rb'
    - 'create_*.rb'
    - 'quickstart_*.rb'

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'examples/**/*'

Metrics/ClassLength:
  Max: 220
  Exclude:
    - 'spec/**/*'

# Metrics/AbcSize configured below

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Lint/MissingSuper:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

# RSpec configuration - relaxed for library specs
RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/MessageSpies:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

# Disable Capybara cops (not needed for this library)
RSpec/Capybara:
  Enabled: false

Capybara:
  Enabled: false

# Relax metrics for complex methods
Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'examples/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 6

# Allow longer methods in specific cases
Naming/PredicateMethod:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2

Style/FormatStringToken:
  Enabled: false