require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'test_*.rb'
    - 'create_*.rb'
    - 'quickstart_*.rb'

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'examples/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Exclude:
    - 'examples/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Lint/MissingSuper:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false