name: Ruby Gem

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    environment: release

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Build gem
      run: gem build *.gemspec

    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: '*.gem'
        generate_release_notes: true

    - name: Publish to RubyGems (Trusted Publishing)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: rubygems/release-gem@v1

    - name: Publish to GitHub Package Registry
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      continue-on-error: true
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} pkg/*.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{ secrets.GITHUB_TOKEN }}"
